site_name: Cambion
theme:
  name: readthedocs
  prev_next_buttons_location: none
nav:
- Home: index.md
- 'Installation': installation.md
- 'Usage':
  - 'Basics': usage-basics.md
  - 'Transports': usage-transports.md
  - 'Serializers': usage-serializers.md